### ISSUE TITLE
It's not possible to use a string PK

### ISSUE THREAD

**Issue by caesay** [gnaeus/EntityFramework.CommonTools#1]
By default, Asp.net identity uses string PK data types (guids). There are lots of good reasons for doing so as long as you don't need a clustered index, but it's impossible to do so with this library because it wraps the columns with a nullable operator. 

Example:
```cs
public interface IModificationAuditable<TUserId> : IModificationTrackable where TUserId : struct
{
    TUserId? UpdaterUserId { get; set; }
}
```

If `TUserId` in the above sample is `string`, then it's impossible to declare a property which will satisfy the interface.

**Comment by gnaeus** [comment]
Thanks for your reply!

The library already contains an interface [IModificationAuditable](https://github.com/gnaeus/EntityFramework.CommonTools#imodificationauditabletuserid) for this case:
```cs
interface IModificationAuditable : IModificationTrackable
{
    string UpdaterUser { get; set; }
}
```
Уou are right. It's field `string UpdaterUser { get; set; }` should be named `UpdaterUserId`.

And we need these three interfaces:
```cs
interface ICreationAuditable : ICreationTrackable
{
    string CreatorUserId { get; set; }
}
interface IModificationAuditable : IModificationTrackable
{
    string UpdaterUserId { get; set; }
}
public interface IDeletionAuditable : IDeletionTrackable
{
    string DeleterUserId { get; set; }
}
```

But I do't know how to implement this without breaking changes.

**Comment by gnaeus** [comment]
@caesay, I create version 2.0 of the library. It supports EFCore 2.0 and EntityFramework 6.2.
And also, I fix signatures of auditable entitiy interfaces:
```cs
interface ICreationAuditable : ICreationTrackable
{
    string CreatorUserId { get; set; }
}

interface IModificationAuditable : IModificationTrackable
{
    string UpdaterUserId { get; set; }
}

public interface IDeletionAuditable : IDeletionTrackable
{
    string DeleterUserId { get; set; }
}
```

So we can use it with ASP.NET Identity.
